#!/bin/bash

TOKEN="$RT3_TOKEN"
DEVKEY="$RT3_DEVKEY"

curl -s -H "token:$TOKEN" \
     -H "developerkey:$DEVKEY" \
     https://api.remot3.it/apv/v27/device/list/all | jq '.devices[6] .devicestate'

# device # 6 is my desired  device to test. Can be edited.
