#!/bin/bash

DEVKEY="MjJGRDM3MjItNDNBNS00NUMzLTk0QzItN0E0NkRBN0EzRTMw"
USERNAME=RT3_EMAIL
PASSWORD=RT3_PASSWD

x = $(curl -s -X POST -H developerkey:"$DEVKEY" -H Content-Type:application/json \
    -H Cache-Control:no-cache -d "{ \"username\":\"$USERNAME\", \
    \"password\":\"$PASSWORD\" }" https://api.remot3.it/apv/v27/user/login | jq -r '.token')

# delete last line
sed '$d' ~/.rt3_setup

#update creds
echo "RT3_TOKEN=$x" >> ~/.rt3_setup && . ~/.rt3_setup
